---
codenotary:
    signer: "red.avtovo@gmail.com"

build_from:
    amd64: "ghcr.io/hassio-addons/base-python/amd64:13.1.3"
    aarch64: "ghcr.io/hassio-addons/base-python/aarch64:13.1.3"
    armv7: "ghcr.io/hassio-addons/base-python/armv7:13.1.3"
