---
codenotary:
    signer: "red.avtovo@gmail.com"

build_from:
    amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
    aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"

args:
    HEV_VERSION: "2.10.1"
