---
name: "Xray Configurator"
version: "1.0.0"
slug: "xray-configurator"
description: |
  Xray Configuration Generator
  
  Web interface to convert VLESS and Shadowsocks links to Xray configuration files.
  Supports both JSON and base64 output formats with copy-to-clipboard functionality.
init: false
startup: services
arch:
  - aarch64
  - amd64
map: 
  - addon_config:rw
boot: auto
codenotary: "red.avtovo@gmail.com"
image: "ghcr.io/j0rsa/xray-configurator-{arch}"
udev: false
url: https://github.com/j0rsa/home-assistant-addons
webui: "http://[HOST]:[PORT:8099]/"
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web UI port
ingress: true
ingress_port: 8099
panel_icon: mdi:web-box