---
codenotary:
    signer: "red.avtovo@gmail.com"

build_from:
    amd64: "ghcr.io/home-assistant/amd64-base-ubuntu:20.04"
    aarch64: "ghcr.io/home-assistant/aarch64-base-ubuntu:20.04"
    armv7: "ghcr.io/home-assistant/armv7-base-ubuntu:20.04"