---
name: "Ollama UI"
version: "0.0.1"
slug: "ollama-ui"
description: |
  Ollama Web UI
  
  A web UI for Ollama. Requires Ollama Add-On to be installed.
arch:
  - aarch64
  - amd64
ingress: true
ingress_entry: "ollama-ui"
panel_icon: "mdi:forum"
panel_title: "Ollama UI"
boot: auto
map: 
  - share:rw
environment:
  OLLAMA_API_URL: "http://d4005b6b-ollama:11434"
codenotary: "red.avtovo@gmail.com"
image: "ghcr.io/j0rsa/ollama-ui-{arch}"
udev: false
url: https://github.com/j0rsa/home-assistant-addons
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web serveer port
