---
name: "Ollama UI"
version: "0.0.10"
slug: "ollama_ui"
description: |
  Ollama Web UI
  
  A web UI for Ollama. Requires Ollama Add-On to be installed.
arch:
  - aarch64
  - amd64
boot: auto
map: 
  - share:rw
options:
  ollama_api_url: "http://d4005b6b-ollama:11434"
schema:
  ollama_api_url: str?
codenotary: "red.avtovo@gmail.com"
image: "ghcr.io/j0rsa/ollama-ui-{arch}"
ports:
  8080/tcp: 5000
ports_description:
  8080/tcp: Web UI port
udev: false
url: https://github.com/j0rsa/home-assistant-addons
webui: http://[HOST]:[PORT:5000]/
