---
name: "Ollama UI"
version: "0.0.7"
slug: "ollama-ui"
description: |
  Ollama Web UI
  
  A web UI for Ollama. Requires Ollama Add-On to be installed
arch:
  - aarch64
  - amd64
boot: auto
map: 
  - share:rw
environment:
  OLLAMA_API_URL: "http://d4005b6b-ollama:11434"
codenotary: "red.avtovo@gmail.com"
image: "ghcr.io/j0rsa/ollama-ui-{arch}"
ports:
  8080/tcp: 5000
ports_description:
  8080/tcp: Web UI port
udev: false
url: https://github.com/j0rsa/home-assistant-addons
webui: http://[HOST]:[PORT:5000]/