---
codenotary:
    signer: "red.avtovo@gmail.com"

build_from:
    amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.21"
    aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.21"
